---
title: "Tour de France"
author: "Poonam Shah"
date: "4/13/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
theme_set(theme_minimal())

```

```{r data chunk }

tdf_winners <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-07/tdf_winners.csv')


```

```{r Wrangling the data and plot}

tdf_winners %>%
  arrange(stage_wins) %>%
  select(nationality, stage_wins)-> winners

winners %>%
  ggplot(aes(x=nationality, y=stage_wins, color=nationality)) +
  geom_point()+
  geom_line()+
  coord_flip()+
  labs(x="", y="Number of Stage Wins", title = "The number of wins by country") +
  theme(legend.position = "none")-> Tour_de_France_plot

print(Tour_de_France_plot)

ggsave("Tour_de_France.png", Tour_de_France_plot)
```



This week Tidy Tuesday was looking at the data set of the Tour de France. The plot looked at the nationality vs Stage Wins. I wanted to make a simple graph, the dataset was perfect for it. In class I will over think the data. This time I wanted to make a simple one. 


